# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-14 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20180104_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
    ]
